
obj-$(CONFIG_LCDKIT_DRIVER)	+= core/common/
subdir-ccflags-y += -Wno-visibility -Wno-enum-conversion -Wno-missing-braces\
-Wno-incompatible-pointer-types -Wno-incompatible-pointer-types-discards-qualifiers 